exclude: "docs|node_modules|migrations|.git|.tox|styles.css"
default_stages: [commit]
fail_fast: false
default_language_version:
  python: "python3.11"

repos:

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
    -   id: mypy


  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        args: ["--fix"]
      # Run the formatter.
      - id: ruff-format
